name: Daily Link Runner

on:
  schedule:
    - cron: "0 9 * * *"  # Runs at 10AM Nigerian time (UTC+1)
  workflow_dispatch:      # Allows manual runs if needed

jobs:
  run-daily-link:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python open_link.py
